import { CreditCard, Download, Search } from "lucide-react";

const payments = [["OrbitAI", "Growth", "$49.00", "Paid"], ["Northstar Fintech", "Enterprise", "$149.00", "Paid"], ["PixelCart", "Pro", "$19.00", "Pending"], ["DevForge", "Premium", "$39.00", "Paid"]];

export default function AdminPaymentsPage() {
  return <div><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><Header title="Payments" subtitle="Track subscription revenue, invoices, and payment status." /><button className="inline-flex w-fit items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium text-zinc-200 hover:bg-white/10"><Download size={16} /> Export report</button></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3">{[["Monthly revenue", "$18,420"], ["Successful payments", "312"], ["Payment success rate", "98.6%"]].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><CreditCard size={20} className="text-indigo-300" /><p className="mt-4 text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-zinc-500">{label}</p></div>)}</div>
    <label className="mt-6 flex max-w-md items-center gap-2 rounded-xl border border-white/10 bg-black px-3 py-2 text-zinc-500"><Search size={17} /><input className="w-full bg-transparent text-sm text-white outline-none" placeholder="Search payments" /></label>
    <div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-white/10 text-zinc-500"><tr><th>Customer</th><th>Plan</th><th>Amount</th><th>Status</th><th>Invoice</th></tr></thead><tbody className="divide-y divide-white/10">{payments.map(([customer, plan, amount, status]) => <tr key={customer}><td className="font-medium text-white">{customer}</td><td className="text-zinc-400">{plan}</td><td className="text-zinc-200">{amount}</td><td><span className={`rounded-full border px-3 py-1 text-xs ${status === "Paid" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" : "border-amber-500/30 bg-amber-500/10 text-amber-300"}`}>{status}</span></td><td><button className="text-sm text-indigo-300 hover:text-indigo-200">Download</button></td></tr>)}</tbody></table></div>
  </div>;
}
function Header({ title, subtitle }: { title: string; subtitle: string }) { return <div><p className="text-sm font-medium text-indigo-400">Administration</p><h1 className="mt-2 text-3xl font-semibold md:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-zinc-400">{subtitle}</p></div>; }
